# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec08596a4b0a0227206f77c593259dc9b6a02e2156da1c3515d425e644cf107ff0f7b1b110c16f5dbcc2bbf68fa50d32918961130c75189e6a753b28361844f

test:
  secret_key_base: e400ef99f67e92695eef3d41b97cb15a0814a616c31f3aef9cd7132de5313a7b1fda427063a5e72641624b3e94a7137dd8d892481a17d639079997c2eeafc17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
